language: go

go:
  - 1.11
  - 1.12
  - tip

before_install:
  - go get -t -v ./...
  - make npm-install

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - - make npm-coverage
